#!/bin/sh
#
# @name TJL Vtol
#
# @type VTOL Tiltrotor
# @class VTOL
#
# @maintainer zhangjianfei <zhangjianfei2005@126.com>
#
# @output MAIN1 Motor right
# @output MAIN2 Motor left
# @output MAIN3 Motor back
# @output MAIN4 empty
#
# @output AUX1 Tilt servo right
# @output AUX2 Tilt servo left
# @output AUX3 Elevon
# @output AUX4 V-Rudder right
# @output AUX5 V-Rudder left
#

sh /etc/init.d/rc.vtol_defaults

if [ $AUTOCNF = yes ]
then
	param set FW_ARSP_MODE 0

	param set FW_L1_PERIOD 17
	param set FW_MAN_R_MAX 50
	param set FW_ACRO_X_MAX   270
	param set FW_ACRO_Y_MAX   270
	param set FW_ACRO_Z_MAX   180
	param set FW_PR_FF    0.5
	param set FW_PR_P 0.08
	param set FW_PSP_OFF  5
	param set FW_P_LIM_MAX    30
	param set FW_P_LIM_MIN    -30
	param set FW_P_RMAX_NEG   60
	param set FW_P_RMAX_POS   60
	param set FW_RR_FF    0.33
	param set FW_RR_P 0.11
	param set FW_YR_FF    0.3
	param set FW_YR_P 0.05

	param set MC_PITCHRATE_D  0.003
	param set MC_PITCHRATE_P  0.15
	param set MC_PITCH_P  6
	param set MC_ROLLRATE_D   0.003
	param set MC_ROLLRATE_P   0.15
	param set MC_ROLL_P   6
	param set MC_YAWRATE_MAX  120
	param set MC_YAWRATE_P    0.3
	param set MC_YAW_P    2.5

	param set MPC_LAND_SPEED 1.2
	param set MPC_TKO_SPEED 2.5
	param set MPC_Z_VEL_MAX_UP 3

	param set SENS_BOARD_ROT 2

	param set PWM_RATE 400
    	param set PWM_AUX_DIS1 1950
    	param set PWM_AUX_DIS2 1950

	param set VT_F_TRANS_DUR  5
	param set VT_FW_DIFTHR_EN 1
	param set VT_FW_DIFTHR_SC 0.17
	param set VT_FW_PERM_STAB 0
	param set VT_TILT_FW  1
	param set VT_TILT_MC  0
	param set VT_TRANS_P2_DUR 1
	param set VT_ELEV_MC_LOCK 0
	param set VT_TYPE 1

	param set VT_MOT_ID 123
	param set VT_IDLE_PWM_MC 1200

	param set VT_FW_MOT_OFFID 3

	param set VT_TRANS_MIN_TM 5
	param set VT_ARSP_TRANS 12
	param set VT_TILT_TRANS   0.5
	param set VT_F_TR_OL_TM   18

	param set VT_B_TRANS_DUR  1
fi

set MAV_TYPE 21

set MIXER vtol_tjl
set MIXER_AUX vtol_tjl

set PWM_OUT 1234
set PWM_AUX_OUT 12345

set PWM_AUX_DISARMED 1500
set PWM_AUX_MIN 1000
set PWM_AUX_MAX 2000
set PWM_AUX_RATE 50
